POST http://213.159.215.231:8080/orders_service/orders/request HTTP/1.1
Content-Type: application/json

{
    "id": "01901160-bf0b-7c72-ba93-2158a76f4cb8",
    "fio": "Иванова И.И.",
    "path_from": "nd93876286",
    "path_to": "nd77715428",
    "request_date": "2024-06-19T10:30:00",
    "employees_count": 1
}