[package]
name = "rust_services"
version = "0.1.0"
edition = "2021"
authors = ["Alex_Xar <P40b0s@gmail.com>"]

[workspace]
members = [
    "db",
    "station_service",
    "order_service",
    "gateway", 
    "service_registrator"
]
