POST http://localhost:8080/register_service HTTP/1.1
content-type: application/json

{ 
    "name":"subway",
    "address":"localhost:8888",
    "endpoints":
    [
        {
            "path":"nearest",
            "authorization":false
        },
        {
            "path":"stations",
            "authorization":false
        },
        {
            "path":"path",
            "authorization":false
        }
    ]
}